language: python
python: 3.6
install:
    - pip install coverage
    - pip install -r requirements.txt
script:
    - pytest tests
    - coverage run -m pytest simple_pp tests
env:
    - CODECOV_TOKEN="70677580-a4d4-449a-aa2f-d8d63a7020ed"
after_success:
    - codecov